/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as publicIndexRouteImport } from './routes/(public)/index';

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport
} as any);

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/(public)/': typeof publicIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/';
  id: '__root__' | '/(public)/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  publicIndexRoute: typeof publicIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof publicIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicIndexRoute: publicIndexRoute
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
