/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicDashboardRouteImport } from './routes/(public)/dashboard'
import { Route as publicLearnIndexRouteImport } from './routes/(public)/learn/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as authAuthAnalyticsIndexRouteImport } from './routes/(auth)/_auth/analytics/index'
import { Route as authAuthAudio_assetsIndexRouteImport } from './routes/(auth)/_auth/audio_assets/index'
import { Route as authAuthGesturesIndexRouteImport } from './routes/(auth)/_auth/gestures/index'
import { Route as authAuthImage_assetsIndexRouteImport } from './routes/(auth)/_auth/image_assets/index'
import { Route as authAuthLessonsIndexRouteImport } from './routes/(auth)/_auth/lessons/index'
import { Route as authAuthAudio_assetsEditIdRouteImport } from './routes/(auth)/_auth/audio_assets/edit/$id'
import { Route as authAuthGesturesEditIdRouteImport } from './routes/(auth)/_auth/gestures/edit/$id'
import { Route as authAuthImage_assetsEditIdRouteImport } from './routes/(auth)/_auth/image_assets/edit/$id'
import { Route as authAuthLessonsEditIdRouteImport } from './routes/(auth)/_auth/lessons/edit/$id'

const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDashboardRoute = publicDashboardRouteImport.update({
  id: '/(public)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLearnIndexRoute = publicLearnIndexRouteImport.update({
  id: '/(public)/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthAnalyticsIndexRoute = authAuthAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAudio_assetsIndexRoute =
  authAuthAudio_assetsIndexRouteImport.update({
    id: '/audio_assets/',
    path: '/audio_assets/',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthGesturesIndexRoute = authAuthGesturesIndexRouteImport.update({
  id: '/gestures/',
  path: '/gestures/',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthImage_assetsIndexRoute =
  authAuthImage_assetsIndexRouteImport.update({
    id: '/image_assets/',
    path: '/image_assets/',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthLessonsIndexRoute = authAuthLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAudio_assetsEditIdRoute =
  authAuthAudio_assetsEditIdRouteImport.update({
    id: '/audio_assets/edit/$id',
    path: '/audio_assets/edit/$id',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthGesturesEditIdRoute = authAuthGesturesEditIdRouteImport.update({
  id: '/gestures/edit/$id',
  path: '/gestures/edit/$id',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthImage_assetsEditIdRoute =
  authAuthImage_assetsEditIdRouteImport.update({
    id: '/image_assets/edit/$id',
    path: '/image_assets/edit/$id',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthLessonsEditIdRoute = authAuthLessonsEditIdRouteImport.update({
  id: '/lessons/edit/$id',
  path: '/lessons/edit/$id',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof publicDashboardRoute
  '/': typeof publicIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/learn/': typeof publicLearnIndexRoute
  '/analytics/': typeof authAuthAnalyticsIndexRoute
  '/audio_assets/': typeof authAuthAudio_assetsIndexRoute
  '/gestures/': typeof authAuthGesturesIndexRoute
  '/image_assets/': typeof authAuthImage_assetsIndexRoute
  '/lessons/': typeof authAuthLessonsIndexRoute
  '/audio_assets/edit/$id': typeof authAuthAudio_assetsEditIdRoute
  '/gestures/edit/$id': typeof authAuthGesturesEditIdRoute
  '/image_assets/edit/$id': typeof authAuthImage_assetsEditIdRoute
  '/lessons/edit/$id': typeof authAuthLessonsEditIdRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof publicDashboardRoute
  '/': typeof publicIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/learn': typeof publicLearnIndexRoute
  '/analytics': typeof authAuthAnalyticsIndexRoute
  '/audio_assets': typeof authAuthAudio_assetsIndexRoute
  '/gestures': typeof authAuthGesturesIndexRoute
  '/image_assets': typeof authAuthImage_assetsIndexRoute
  '/lessons': typeof authAuthLessonsIndexRoute
  '/audio_assets/edit/$id': typeof authAuthAudio_assetsEditIdRoute
  '/gestures/edit/$id': typeof authAuthGesturesEditIdRoute
  '/image_assets/edit/$id': typeof authAuthImage_assetsEditIdRoute
  '/lessons/edit/$id': typeof authAuthLessonsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(public)/dashboard': typeof publicDashboardRoute
  '/(public)/': typeof publicIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(public)/learn/': typeof publicLearnIndexRoute
  '/(auth)/_auth/analytics/': typeof authAuthAnalyticsIndexRoute
  '/(auth)/_auth/audio_assets/': typeof authAuthAudio_assetsIndexRoute
  '/(auth)/_auth/gestures/': typeof authAuthGesturesIndexRoute
  '/(auth)/_auth/image_assets/': typeof authAuthImage_assetsIndexRoute
  '/(auth)/_auth/lessons/': typeof authAuthLessonsIndexRoute
  '/(auth)/_auth/audio_assets/edit/$id': typeof authAuthAudio_assetsEditIdRoute
  '/(auth)/_auth/gestures/edit/$id': typeof authAuthGesturesEditIdRoute
  '/(auth)/_auth/image_assets/edit/$id': typeof authAuthImage_assetsEditIdRoute
  '/(auth)/_auth/lessons/edit/$id': typeof authAuthLessonsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/api/trpc/$'
    | '/learn/'
    | '/analytics/'
    | '/audio_assets/'
    | '/gestures/'
    | '/image_assets/'
    | '/lessons/'
    | '/audio_assets/edit/$id'
    | '/gestures/edit/$id'
    | '/image_assets/edit/$id'
    | '/lessons/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/'
    | '/api/trpc/$'
    | '/learn'
    | '/analytics'
    | '/audio_assets'
    | '/gestures'
    | '/image_assets'
    | '/lessons'
    | '/audio_assets/edit/$id'
    | '/gestures/edit/$id'
    | '/image_assets/edit/$id'
    | '/lessons/edit/$id'
  id:
    | '__root__'
    | '/(auth)/_auth'
    | '/(public)/dashboard'
    | '/(public)/'
    | '/api/trpc/$'
    | '/(public)/learn/'
    | '/(auth)/_auth/analytics/'
    | '/(auth)/_auth/audio_assets/'
    | '/(auth)/_auth/gestures/'
    | '/(auth)/_auth/image_assets/'
    | '/(auth)/_auth/lessons/'
    | '/(auth)/_auth/audio_assets/edit/$id'
    | '/(auth)/_auth/gestures/edit/$id'
    | '/(auth)/_auth/image_assets/edit/$id'
    | '/(auth)/_auth/lessons/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
  publicDashboardRoute: typeof publicDashboardRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  publicLearnIndexRoute: typeof publicLearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/dashboard': {
      id: '/(public)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof publicDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/learn/': {
      id: '/(public)/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof publicLearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/analytics/': {
      id: '/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof authAuthAnalyticsIndexRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/audio_assets/': {
      id: '/(auth)/_auth/audio_assets/'
      path: '/audio_assets'
      fullPath: '/audio_assets/'
      preLoaderRoute: typeof authAuthAudio_assetsIndexRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/gestures/': {
      id: '/(auth)/_auth/gestures/'
      path: '/gestures'
      fullPath: '/gestures/'
      preLoaderRoute: typeof authAuthGesturesIndexRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/image_assets/': {
      id: '/(auth)/_auth/image_assets/'
      path: '/image_assets'
      fullPath: '/image_assets/'
      preLoaderRoute: typeof authAuthImage_assetsIndexRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/lessons/': {
      id: '/(auth)/_auth/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof authAuthLessonsIndexRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/audio_assets/edit/$id': {
      id: '/(auth)/_auth/audio_assets/edit/$id'
      path: '/audio_assets/edit/$id'
      fullPath: '/audio_assets/edit/$id'
      preLoaderRoute: typeof authAuthAudio_assetsEditIdRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/gestures/edit/$id': {
      id: '/(auth)/_auth/gestures/edit/$id'
      path: '/gestures/edit/$id'
      fullPath: '/gestures/edit/$id'
      preLoaderRoute: typeof authAuthGesturesEditIdRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/image_assets/edit/$id': {
      id: '/(auth)/_auth/image_assets/edit/$id'
      path: '/image_assets/edit/$id'
      fullPath: '/image_assets/edit/$id'
      preLoaderRoute: typeof authAuthImage_assetsEditIdRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/lessons/edit/$id': {
      id: '/(auth)/_auth/lessons/edit/$id'
      path: '/lessons/edit/$id'
      fullPath: '/lessons/edit/$id'
      preLoaderRoute: typeof authAuthLessonsEditIdRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthAnalyticsIndexRoute: typeof authAuthAnalyticsIndexRoute
  authAuthAudio_assetsIndexRoute: typeof authAuthAudio_assetsIndexRoute
  authAuthGesturesIndexRoute: typeof authAuthGesturesIndexRoute
  authAuthImage_assetsIndexRoute: typeof authAuthImage_assetsIndexRoute
  authAuthLessonsIndexRoute: typeof authAuthLessonsIndexRoute
  authAuthAudio_assetsEditIdRoute: typeof authAuthAudio_assetsEditIdRoute
  authAuthGesturesEditIdRoute: typeof authAuthGesturesEditIdRoute
  authAuthImage_assetsEditIdRoute: typeof authAuthImage_assetsEditIdRoute
  authAuthLessonsEditIdRoute: typeof authAuthLessonsEditIdRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthAnalyticsIndexRoute: authAuthAnalyticsIndexRoute,
  authAuthAudio_assetsIndexRoute: authAuthAudio_assetsIndexRoute,
  authAuthGesturesIndexRoute: authAuthGesturesIndexRoute,
  authAuthImage_assetsIndexRoute: authAuthImage_assetsIndexRoute,
  authAuthLessonsIndexRoute: authAuthLessonsIndexRoute,
  authAuthAudio_assetsEditIdRoute: authAuthAudio_assetsEditIdRoute,
  authAuthGesturesEditIdRoute: authAuthGesturesEditIdRoute,
  authAuthImage_assetsEditIdRoute: authAuthImage_assetsEditIdRoute,
  authAuthLessonsEditIdRoute: authAuthLessonsEditIdRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
  publicDashboardRoute: publicDashboardRoute,
  publicIndexRoute: publicIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  publicLearnIndexRoute: publicLearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
